RDKB-33527: Fix moca build failure
Reason for change:
Moca build is failed for few platforms due to lack of ccsp_common lib linking

12:01:37 | /mnt/********/workspace/ARRISXB3COX-Yocto-Build/build-arrisxb3-cox/tmp/sysroots/x86_64-linux/usr/bin/arm1176jzstb-rdk-linux-uclibceabi/../../libexec/arm1176jzstb-rdk-linux-uclibceabi/gcc/armeb-rdk-linux-uclibceabi/4.8.4/ld: mrd.o: undefined reference to symbol 'shmid'
12:01:37 | /mnt/********/workspace/ARRISXB3COX-Yocto-Build/build-arrisxb3-cox/tmp/sysroots/arrisxb3arm-cox/usr/lib/libccsp_common.so.0: error adding symbols: DSO missing from command line

Test Procedure:
Risks: Low
Signed-off-by:Veeraputhiran_Thangavel@comcast.com

(cherry picked from commit f180c2f3394d02fbe6368c3e0f8609ed47ccd73e)
Change-Id: Ib7da0b436a9c38d790fb57f6af2734860824f0f0